[package]
name = "red"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = "1.4.13"
fltk-theme = "0.7"

[profile.release]
strip = true

[patch.crates-io]
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }