[package]
name = "red"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = "1.4.13"
fltk-theme = "0.7"
regex = "1.9.6"
notify = "5.1"
# optional deps
# term
portable-pty = { version = "0.8", optional = true }
vte = { version = "0.12.0", optional = true }
# highlight
tree-sitter-highlight = { version = "0.20", optional = true }
tree-sitter-rust = { version = "0.20", optional = true }
tree-sitter-toml = { version = "0.20", optional = true }
tree-sitter-md = { version = "0.1", optional = true }

[features]
default = ["highlight", "term"]
highlight = [
    "tree-sitter-highlight", 
    "tree-sitter-rust", 
    "tree-sitter-toml", 
    "tree-sitter-md",
    ]
term = [
    "portable-pty",
    "vte"
]
debug-term = []

[profile.release]
strip = true

[patch.crates-io]
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }