[package]
name = "red"
version = "0.1.0"
edition = "2021"

[dependencies]
fltk = "1.4.13"
fltk-theme = "0.7"
portable-pty = "0.8"
tree-sitter = { version = "0.20", optional = true }
tree-sitter-highlight = { version = "0.20", optional = true }
tree-sitter-rust = { version = "0.20", optional = true }
tree-sitter-toml = { version = "0.20", optional = true }

[features]
default = ["highlight"]
highlight = ["tree-sitter", "tree-sitter-highlight", "tree-sitter-rust", "tree-sitter-toml"]

[profile.release]
strip = true

[patch.crates-io]
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }