[package]
name = "red"
version = "0.1.0"
edition = "2021"

[dependencies]
# fltk = { path = "../fltk-rs/fltk" }
fltk = { git = "https://github.com/fltk-rs/fltk-rs" }
# fltk-theme = "0.7"
portable-pty = { version = "0.8", optional = true }

[profile.release]
strip = true
